### ISSUE TITLE
AtCoder Beginners Selection

### ISSUE THREAD

**Issue by zaki-yama** [zaki-yama/atcoder#4]
[AtCoder Beginners Selection - AtCoder](https://atcoder.jp/contests/abs)

- [ ] ABC086A	Product
- [ ] ABC081A	Placing Marbles
- [x] ABC081B	Shift only　#3 
- [x] ABC087B	Coins #5 
- [x] ABC083B	Some Sums #6 
- [x] ABC088B	Card Game for Two #7 
- [x] ABC085B	Kagami Mochi #8 
- [x] ABC085C	Otoshidama #9 
- [x] ABC049C	白昼夢 #10 
- [x] ABC086C	Traveling #11 

ref. [AtCoder に登録したら次にやること ～ これだけ解けば十分闘える！過去問精選 10 問 ～ #AtCoder - Qiita](https://qiita.com/drken/items/fd4e5e3630d0f5859067)

**Comment by zaki-yama** [comment]
わいわい
